spring:
  application:
    name: kairosmix-backend
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:kairosmix_db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.kairosmix: DEBUG
    org.springframework: INFO
    org.hibernate: WARN
